- platform: command_line
  switches:

    quintanaroostream:
      command_on: "~/Bitol/VirtualDroneSolution/UseCases/XunanKab/Vehicle.sh -i powerup -s 172.17.0.1 -n quintanaroo -c /dev/video1 -p 5000 &"
      command_off: "~/Bitol/VirtualDroneSolution/UseCases/XunanKab/Vehicle.sh -i powerdown -n quintanaroo &"

    quintanaroofacedetect:
      command_on: "~/Bitol/VirtualDroneSolution/UseCases/XunanKab/CcStream.sh -i powerup -v 172.17.0.2 -n quintanaroo -l 5000 -r 5700 &"
      command_off: "~/Bitol/VirtualDroneSolution/UseCases/XunanKab/CcStream.sh -i powerdown -n quintanaroo &"
