FROM ubuntu:16.04

MAINTAINER Abraham Arce <xe1gyq@gmail.com>

ENV TIMEZONE America/Mexico_City

RUN     apt update && \
        apt -y upgrade && \
        apt install -y tightvncserver

CMD ["bash"]
